/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_lib_PhotonHelper */

#ifndef _Included_org_photon_lib_PhotonHelper
#define _Included_org_photon_lib_PhotonHelper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
